on:
  push:
    branches-ignore:
      - 'main'
      - 'release/**'

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: cat README.md
