on:
  push:
    branches:
      - 'main'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.JIRHUB_TOKEN }}

      - name: Generate changelog, bump and tag version
        id: bump
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.JIRHUB_TOKEN }}
          git-message: 'chore(release): {version}'
          preset: 'angular'
          tag-prefix: 'v'
          output-file: 'CHANGELOG.md'
          version-file: 'package.json'
          version-path: 'version'
          skip-version-file: 'false'
          skip-commit: 'false'
          skip-git-pull: 'true'
          skip-on-empty: 'true'
          skip-ci: 'true'
          create-summary: 'true'
          pre-release: 'false'

      - name: Create release
        if: steps.bump.outputs.skipped != 'true'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.bump.outputs.tag }}
          draft: false
          prerelease: false
          generate_release_notes: true
          token: ${{ secrets.JIRHUB_TOKEN }}
