on:
  push:
    branches:
      - 'main'

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Conventional Changelog Action
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.github_token }}
          git-message: 'chore(release): {version}'
          preset: 'angular'
          tag-prefix: 'v'
          output-file: 'CHANGELOG.md'
          version-file: 'package.json'
          version-path: 'version'
          skip-version-file: 'false'
          skip-commit: 'false'
          skip-git-pull: 'true'
          skip-on-empty: 'true'
          skip-ci: 'true'
          create-summary: 'true'
          pre-release: 'false'
